### PR TITLE
chore: cleanup Cargo.toml files

### LINKED ISSUE #33: fix docker aarch64-linux compilation
At some point the platform `aarch64-linux` compilation failed, like in this workflow run: https://github.com/hoprnet/hoprd/actions/runs/26034119831/job/76533091908

To test this kind of build, attach the label `binary:aarch64-linux`

### PR DESCRIPTION
**Pull request by majchrzamemil**
Cleanup of Cargo.toml files. Moving what can be moved to workspace.
Additionally fixed bug https://github.com/hoprnet/hoprd/actions/runs/26034119831/job/76533091908 from recent change. Aarch64 docker build still requires x86 machine

### CODE REVIEW

File: rest-api-client/Cargo.toml [hunk 1]
```diff
@@ -14,8 +17,8 @@ http = { workspace = true }
 percent-encoding = { workspace = true }
 serde_urlencoded = { workspace = true }
 progenitor-client = { workspace = true }
-reqwest = { workspace = true, features = ["json", "stream"] }
-serde = { workspace = true, features = ["derive"] }
```
Comment (Teebor-Choka) [inline rest-api-client/Cargo.toml:18]: The features are kept locally because it narrows the scope for when packages are built individually, and it is a good practice to be explicit about the features in the package cargo.toml, easire to lookup.

Comment (majchrzamemil) [reply rest-api-client/Cargo.toml:18]: Ok, that makes sense - reverting that part

**Review by Teebor-Choka — APPROVED** [review]

**Comment by ausias-armesto** [comment]
Fixes #33
